export  const apiRoutes = {
    APIHOSTNAME : "http://localhost:8081/",
    REGISTRATION : "insertData",
    LOGIN : "login",
    GETPRODUCT : "ProductDalaList",
    GETPRODUCTIMAGES : "getImages",
    GETUSER : "userRegistrationData",
    SHIPADDRESS : "addAddress",
    GETSIZE : "sizeDataTable",
    CHECKOUT : "checkoutUser",
    CHECKPROMOCODE : "promovalidation",
    GETORDERS : "getorderforuser",
    GENERATEINVOICE:"generateInvoice",
    GETALLPRODUCTS : "allproductUser",
    GETFILTERPRODUCTS : "filterProduct",
    GETPRODUCTNAMES : "getProdNameData",
    CONTACTDATA : "usercontact",
    UPDATEPROFILE : "updateData",
    GOLD:"goldProduct",
    SILVER:"silverProduct",
    GETPROMOCODE:"getpromocodes",
    OTPREQUEST:"request_otp",
    OTPVERIFACTION:"verify_otp",
    SETNEWPASSWORD : "set_newpassword",
    REVIEWDATA : "addReview",
    CANCELORDER : "cancel_order",
    GETUSERREVIEW : "UserReviewData",
}